INSERT INTO topics (slug, label, subject, module, grades) VALUES ('order', 'Порядок действий и скобки', 'Математика', 'Башня дробей', '3,4,5') ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, label, subject, module, grades) VALUES ('frac', 'Действия с дробями', 'Математика', 'Башня дробей', '5,6') ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, label, subject, module, grades) VALUES ('percent', 'Задачи на проценты', 'Математика', 'Башня дробей', '5,6,7') ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, label, subject, module, grades) VALUES ('area', 'Площадь и периметр', 'Математика', 'Башня дробей', '4,5,6') ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, label, subject, module, grades) VALUES ('motion', 'Задачи на движение', 'Математика', 'Башня дробей', '4,5,6,7') ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, label, subject, module, grades) VALUES ('negative', 'Отрицательные числа', 'Математика', 'Башня дробей', '6,7') ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, label, subject, module, grades) VALUES ('equation', 'Уравнения', 'Математика', 'Башня дробей', '6,7,8') ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, label, subject, module, grades) VALUES ('nn', 'Правописание -Н- и -НН-', 'Русский язык', 'Гастро-пунктуация', '6,7,8') ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, label, subject, module, grades) VALUES ('comma', 'Запятая перед «что»', 'Русский язык', 'Гастро-пунктуация', '5,6,7') ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, label, subject, module, grades) VALUES ('parts', 'Части речи', 'Русский язык', 'Гастро-пунктуация', '3,4,5') ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, label, subject, module, grades) VALUES ('unstressed', 'Безударные гласные в корне', 'Русский язык', 'Гастро-пунктуация', '3,4,5') ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, label, subject, module, grades) VALUES ('homogeneous', 'Однородные члены предложения', 'Русский язык', 'Гастро-пунктуация', '4,5,6') ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, label, subject, module, grades) VALUES ('participle', 'Деепричастный оборот', 'Русский язык', 'Гастро-пунктуация', '7,8') ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, label, subject, module, grades) VALUES ('chain', 'Пищевые цепи', 'Окружающий мир', 'Био-кликер', '3,4,5') ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, label, subject, module, grades) VALUES ('animals', 'Классификация животных', 'Окружающий мир', 'Био-кликер', '3,4,5') ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, label, subject, module, grades) VALUES ('redbook', 'Красная книга и природа России', 'Окружающий мир', 'Био-кликер', '3,4,5,6') ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, label, subject, module, grades) VALUES ('safety', 'Первая помощь и безопасность', 'Окружающий мир', 'Био-кликер', '3,4,5,6') ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, label, subject, module, grades) VALUES ('cell', 'Строение клетки', 'Окружающий мир', 'Био-кликер', '5,6,7') ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, label, subject, module, grades) VALUES ('kulikovo', 'Куликовская битва', 'История', 'Хроно-битва', '6,7') ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, label, subject, module, grades) VALUES ('nevsky', 'Александр Невский', 'История', 'Хроно-битва', '6,7') ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, label, subject, module, grades) VALUES ('grozny', 'Иван Грозный', 'История', 'Хроно-битва', '7,8') ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, label, subject, module, grades) VALUES ('peter', 'Пётр I и реформы', 'История', 'Хроно-битва', '7,8') ON CONFLICT (slug) DO NOTHING;
